import datetime

from src.department import Department

STUDENT_FIRST_ID = 1
STUDENT_1_FIRSTNAME_VALID = "Jane"
STUDENT_1_LASTNAME_VALID = "Doe"
STUDENT_1_DATEOFBIRTH_VALID = datetime.date(2005, 1, 31)
STUDENT_1_EMAILADDRESS_VALID = "jdoe@gmail.com"
STUDENT_1_HOMEADDRESS_VALID = "1 Main Street, Smalltown, MA, 01234"
STUDENT_1_HOMEADDRESS_INVALID = ""
	
COURSE_1_TITLE = str(Department.COMPUTER_SCIENCE.name) + " 429"
COURSE_1_NUMBEROFCREDITS_VALID = 4
COURSE_1_NUMBEROFCREDITS_INVALID = -1
	
COURSE_1_COURSESECTION_1_ENROLLMENTCAP_VALID = 3
COURSE_1_COURSESECTION_1_ENROLLMENTCAP_INVALID = -1
